# Default values for gitops-agent.
# This is a YAML-formatted file.

replicaCount: 1

# The image repository to prepend to images pulled in deployments.  Such as a DockerHub proxy in Artifactory or Nexus.
# Example:
# imageRepo: "artifactory.corp.net/dockerhub-proxy/"
imageRepo: ""

argocd:
  image: argoproj/argocd:v2.7.8

  # Disable to prevent this chart install from creating and updating Argo CustomResourceDefinitons (CRDs)
  # This is needed for multiple chart installs to a single cluster or namespaced agents.
  # In the case of multiple charts being installed into one cluster, only one install should manage the CRDs
  manageCRDs: true

redis:
  image: redis:6.2.12-alpine

harness:
  # REQUIRED: The ID of the Harness account where the agent will connect.
  # Can be obtained from the URL of your Harness account: https://app.harness.io/ng/account/<accountId>/main-dashboard
  accountId: ""

  # Optional: Identifier of the Harness Organization to install the agent into
  orgId: ""

  # Optional: Identifier of the Harness Project to install the agent into
  projectId: ""

  # URL of the Harness manager for Self Managed Platform installs.  Only needed for SMP installs.
  smpManagerURL: ""

  # PEM formatted bundle of certificates to trust on the agent. Such as self signed certs, or the CA cert and intermediate certificates used to sign internal traffic in your organization.  Needed for SMP installs or proxies doing TLS interception
  certBundle: "" #|
    # -----BEGIN CERTIFICATE-----  
    # XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    # -----END CERTIFICATE-------  
    # -----BEGIN CERTIFICATE-----  
    # XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    # -----END CERTIFICATE-------

  # Optional: List of repository server hostnames to trust, signed by the certificates listed above.  Hostnames in this list will automatically be added to the list of Repository Certificates.
  repoServers: []
  # - server1.corp.net
  # - server2.corp.net

  agent:
    # Image path to the Harness GitOps Agent image
    image: harness/gitops-agent:v0.56.7

    # REQUIRED: Identifier of the GitOps agent to register with Harness
    identifier: ""

    # REQUIRED: GitOps Agent Token for GitOps agent to connect to Harness control plane.
    gitOpsAgentToken: ""

    # Harness manager URLs.  These are overridden when "harness.smpManagerURL" is set
    httpTarget: https://app.harness.io/gitops
    grpcTarget: app.harness.io:443
    grpcAuthority: gratis-gitops-grpc-app.harness.io

    # Agent auto upgrader
    upgrader:
      enabled: true
      # Image path to the agent upgrader image
      image: harness/upgrader:latest

nameOverride: ""
fullnameOverride: ""
