apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: gitops-agent-secret
    app.kubernetes.io/part-of: argocd
  name: {{ include "gitops-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GITOPS_AGENT_TOKEN: |
    {{ .Values.harness.agent.gitOpsAgentToken }}
---
{{- if .Values.harness.certBundle -}}
apiVersion: v1
kind: Secret
metadata:
  name: addcerts
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ca.bundle: |
{{ .Values.harness.certBundle | indent 4 }}
{{- end }}